version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'python3'
    tty: true
    volumes:
      - .:/app
    ports: 
      - '4000:80'
    networks:
      - my-first-network
networks:
  my-first-network:
      external: true
